name: Build release zip

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build plugin
        run: |
          composer install --no-dev
          rm dev-composer.json
          rm dev-composer.sh
          rm phpcs.xml.dist
          rm phpstan.neon

      - name: ZIP plugin
        run: |
          cd ..
          zip -urq ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/* -x "*/.git/*" "*/.github/*" "*/phpcs.xml" "*/composer.json" "*/composer.lock" "*/readme.md" "*/.gitignore" "*/vendor/*"
          zip -urq ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/vendor/composer/*
          zip -urq ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/vendor/threadi/easy-setup-for-wordpress/
          cp ${{ github.event.repository.name }}.zip ${{ github.event.repository.name }}/

      - name: Create Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ github.event.repository.name }}.zip